[unix_http_server]
file=/tmp/supervisor-voice-text-processor.sock

[supervisord]
logfile=/tmp/supervisord-voice-text-processor.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/tmp/supervisord-voice-text-processor.pid
nodaemon=false
silent=false

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor-voice-text-processor.sock

[include]
files = %(here)s/supervisor/*.conf
